name: zds_flutter_example

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  lottie: ^2.1.0
  table_calendar: ^3.0.9
  zds_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true
