# name: "Release"

# on:
#   push:
#     # tags:
#     #   - "**"±TODO:

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.13.x"
#           channel: "stable"
#       - name: Setup flutter
#         run: flutter pub get
#       - name: build
#         run: |
#           cd example
#           flutter build web -o ../build --no-tree-shake-icons --base-href "/zds_flutter/"
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: build
#       - name: Publish
#         run: |
#           dart format .
#           dart fix --apply
#           dart pub publish
